name: 'Gosec Security Checker'
description: 'Runs the gosec security checker'

inputs:
  go-install:
    description: 'Whether Go needs installing. Will need to be set as true if Go has not already been installed.'
    default: false

  go-version:
    description: 'The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.'
  go-version-file:
    description: 'Path to the go.mod or go.work file.'
  go-cache-dependency-path:
    description: 'Used to specify the path to a dependency file - go.sum'
  go-check-latest:
    description: 'Set this option to true if you want the action to always check for the latest available version that satisfies the version spec'
    default: false
  go-cache:
    description: Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
    default: true

  working-directory:
    description: 'Directory in which to run gosec'
    default: '.'
  go-package:
    description: 'Go Package to scan with gosec'
    default: './...'

runs:
  using: "composite"
  steps:
    - if: inputs.go-install == 'true'
      uses: actions/setup-go@v4.0.0
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
        cache-dependency-path: ${{ inputs.go-cache-dependency-path }}
        check-latest: ${{ inputs.go-check-latest }}
        cache: ${{ inputs.go-cache }}

    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      shell: bash

    - name: Run gosec
      run: |
        cd ${{ inputs.working-directory }}
        gosec ${{ inputs.go-package }}
      shell: bash